# Generated by Django 3.0.3 on 2020-09-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='TodoModel',
        ),
    ]
